/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monitor;

import container.Container;
import static container.Container.createWordsArray;
import static container.Reader.readFile;
import static container.WriteData.addFileToBase;
import static container.WriteData.addTextToBase;
import static container.WriteData.saveFileToBase;
import generator.Ngrams;
import generator.Stats;
import generator.TextGenerator;
import static generator.TextGenerator.createNGram;
import static generator.Tree.addNGramToTree;
import static generator.Tree.checkWordsInDictionary;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.Random;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Marta
 */
public class Window extends javax.swing.JFrame {
    private static int[] arrayLength = new int[1];
    private static int[] indeksWordsInSettingsWindow = new int[5];
    private static int[] indeksWordsInSettingsWindow2 = new int[5];
    private static String wordsIn = "";
    private static String wordsInInfo = "";
    private static String newWords = "";
    private static String wordsInSettingsWindow = "";
    private static String wordsInSettingsWindow2 = "";
    private static Container[] con;
    private static Container[] dictionary;
    private static TextGenerator[] textGen;
    private static Ngrams[] n_gram;
    public static TreeSet treeSet = null;
    public static TreeSet treeDictionary = null;
    private static int rankOfN_gram = 2;
    

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        setName("ChatMe");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Quit = new java.awt.Button();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelChat = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSend = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneJulian = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaMy = new javax.swing.JTextArea();
        jPanelSettings = new javax.swing.JPanel();
        jPanelStatistics = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemAdd = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemAuthor = new javax.swing.JMenuItem();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Quit.setActionCommand("QuitButton");
        Quit.setLabel("Quit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });

        jPanelChat.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monitor/jul2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jButtonSend.setText("Send");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jTextPaneJulian.setForeground(new java.awt.Color(51, 204, 255));
        jScrollPane2.setViewportView(jTextPaneJulian);

        jTextAreaMy.setColumns(20);
        jTextAreaMy.setRows(5);
        jScrollPane4.setViewportView(jTextAreaMy);

        javax.swing.GroupLayout jPanelChatLayout = new javax.swing.GroupLayout(jPanelChat);
        jPanelChat.setLayout(jPanelChatLayout);
        jPanelChatLayout.setHorizontalGroup(
            jPanelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChatLayout.createSequentialGroup()
                .addGroup(jPanelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChatLayout.createSequentialGroup()
                        .addContainerGap(402, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelChatLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
            .addGroup(jPanelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChatLayout.createSequentialGroup()
                    .addContainerGap(30, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(279, Short.MAX_VALUE)))
        );
        jPanelChatLayout.setVerticalGroup(
            jPanelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChatLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelChatLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jButtonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChatLayout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(173, Short.MAX_VALUE)))
        );

        jTabbedPane.addTab("Chat", jPanelChat);

        javax.swing.GroupLayout jPanelSettingsLayout = new javax.swing.GroupLayout(jPanelSettings);
        jPanelSettings.setLayout(jPanelSettingsLayout);
        jPanelSettingsLayout.setHorizontalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        jPanelSettingsLayout.setVerticalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Settings", jPanelSettings);

        javax.swing.GroupLayout jPanelStatisticsLayout = new javax.swing.GroupLayout(jPanelStatistics);
        jPanelStatistics.setLayout(jPanelStatisticsLayout);
        jPanelStatisticsLayout.setHorizontalGroup(
            jPanelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        jPanelStatisticsLayout.setVerticalGroup(
            jPanelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Statistics", jPanelStatistics);

        jMenu1.setText("File");

        jMenuItemOpen.setText("Open file");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOpen);

        jMenuItemAdd.setText("Add file");
        jMenu1.add(jMenuItemAdd);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuHelp.setText("About");

        jMenuItem1.setText("Program");
        jMenuHelp.add(jMenuItem1);

        jMenuItemAuthor.setText("Author");
        jMenuHelp.add(jMenuItemAuthor);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Quit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Quit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
    Object source = evt.getSource();
    int ask = JOptionPane.showConfirmDialog(this, "Are you quit?", "quit", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
    if(ask == JOptionPane.YES_OPTION) 
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_QuitActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        Object source = evt.getSource();
        if(source == jButtonSend) {
            Stats stats = new Stats();
            
            Random rand = new Random();
            String tempWords;
            Date date = new Date();
            
            tempWords = ""+ jTextAreaMy.getText();
            newWords = newWords+ checkWordsInDictionary(treeDictionary, tempWords);
            addTextToBase("base/Base",null, "base", tempWords);
            wordsIn = wordsIn + "\n" + "user:\n" + date + "\n" + jTextAreaMy.getText() + "\n";
            jTextAreaMy.setText("");
            con = createWordsArray(con, "base/Base", arrayLength);

            try {
                n_gram = createNGram(n_gram, con, rankOfN_gram);
            } catch (ArrayIndexOutOfBoundsException aioobe) {

            }
            treeSet = addNGramToTree(treeSet, n_gram, rankOfN_gram);

            stats.findMostCommonNGrams(n_gram); /*tworzy staty*/

            stats.findMostCommonSufiks(n_gram); /*tworzy staty*/

            wordsInSettingsWindow = stats.createStatsArray(n_gram);
            wordsInSettingsWindow2 = stats.createStatsArray2(n_gram);
            for (int i = 0; i < 5; i++) {
                indeksWordsInSettingsWindow[i] = stats.getPointer()[i];
                indeksWordsInSettingsWindow2[i] = stats.getPointerSufiks()[i];
                System.out.println(indeksWordsInSettingsWindow[i]);
            }
            int randInt = 0;
            try {
                randInt = rand.nextInt(arrayLength[0] - rankOfN_gram);
                while (randInt < 0) {
                    randInt = rand.nextInt(arrayLength[0] - rankOfN_gram);
                }
            } catch (IllegalArgumentException iae) {
                randInt = 0;
            }
            try {
                wordsIn = wordsIn + "\n" + "computer:\n" + date + "\n" + n_gram[randInt].getPrefiks() + "\n";
                jTextPaneJulian.setText(wordsIn);
        } catch (NullPointerException npe) {
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        Object source = evt.getSource();
        if (source == jMenuItemOpen) {
            JFileChooser fileChoicer = new JFileChooser();
            if(fileChoicer.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                File file = fileChoicer.getSelectedFile();
                String tmp = null;
                try {
                tmp = readFile(file.getAbsolutePath());
                } catch(IOException ex2) {
                     Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex2);
                }
                
                try {
                    saveFileToBase("base/Base", file, tmp, "base");
                } catch (IOException ex1) {
                    Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }
            con = createWordsArray(con, "base/Base", arrayLength);
            n_gram = createNGram(n_gram, con, rankOfN_gram);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

                                           

    private void jMenuItemAddActionPerformed(java.awt.event.ActionEvent evt) {                                             
        Object source = evt.getSource();
        if(source == jMenuItemAdd) {
            JFileChooser fileChoicer = new JFileChooser();
            if(fileChoicer.showOpenDialog(null)==JFileChooser.APPROVE_OPTION) {
                File file = fileChoicer.getSelectedFile();
                String tmp = null;
                try {
                    tmp = readFile(file.getAbsolutePath());
                } catch (IOException ex) {
                    Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    addFileToBase("base/Base", file, tmp, "base");
                } catch (IOException ex) {
                    Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            con = createWordsArray(con, "base/Base", arrayLength);
            n_gram = TextGenerator.createNGram(n_gram, con, rankOfN_gram);
        }
        // TODO add your handling code here:
    }   
    public static void main(String args[]) {
     Window window = new Window();
        window.setDefaultCloseOperation(EXIT_ON_CLOSE);
        window.setVisible(true);

    }

    public static int getRankOfN_gram() {
        return rankOfN_gram;
    }

    public static void setRankOfN_gram(int rankOfN_gram) {
        Window.rankOfN_gram = rankOfN_gram;
    }

    public static String getWordsInSettingsWindow() {
        return wordsInSettingsWindow;
    }

    public static void setWordsInSettingsWindow(String wordsInSettingsWindow) {
        Window.wordsInSettingsWindow = wordsInSettingsWindow;
    }

    public static int[] getIndeksWordsInSettingsWindow() {
        return indeksWordsInSettingsWindow;
    }

    public static void setIndeksWordsInSettingsWindow(int[] indeksWordsInSettingsWindow) {
        Window.indeksWordsInSettingsWindow = indeksWordsInSettingsWindow;
    }

    public static int[] getIndeksWordsInSettingsWindow2() {
        return indeksWordsInSettingsWindow2;
    }

    public static void setIndeksWordsInSettingsWindow2(int[] indeksWordsInSettingsWindow2) {
        Window.indeksWordsInSettingsWindow2 = indeksWordsInSettingsWindow2;
    }

    public static String getWordsInSettingsWindow2() {
        return wordsInSettingsWindow2;
    }

    public static void setWordsInSettingsWindow2(String wordsInSettingsWindow2) {
        Window.wordsInSettingsWindow2 = wordsInSettingsWindow2;
    }

    public static int[] getArrayLength() {
        return arrayLength;
    }

    public static void setArrayLength(int[] arrayLength) {
        Window.arrayLength = arrayLength;
    }

    public JButton getSendButton() {
        return jButtonSend;
    }

    public void setSendButton(JButton jButtonSend) {
        this.jButtonSend = jButtonSend;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Quit;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAdd;
    private javax.swing.JMenuItem jMenuItemAuthor;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JPanel jPanelChat;
    private javax.swing.JPanel jPanelSettings;
    private javax.swing.JPanel jPanelStatistics;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextAreaMy;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPaneJulian;
    // End of variables declaration//GEN-END:variables
}
